/**
 * @module mockContacts
 * @description Datos wireframe (mock) del Módulo Core CRM — Etapa 2.
 * Array de contactos demo autocontenido para el esqueleto visual de
 * ContactsN2List (Panel N2) y ContactsN3Detail (Panel N3).
 *
 * Se reutiliza el tipo Contact de src/types.ts para mantener consistencia
 * con el modelo de datos del CRM (leadStage, originPlatform, platform, leadLevel).
 */

import type { Contact } from '../../types';

export const DEMO_CRM_CONTACTS: (Contact & { isOnline?: boolean })[] = [
  {
    id: 'contact-1',
    name: 'María Fernanda López',
    email: 'maria.lopez@example.com',
    phone: '+593 99 123 4567',
    city: 'Quito',
    leadType: 'Servicio',
    interest: 'Meta Ads',
    source: 'whatsapp',
    leadStage: 'Contacted',
    purchases: '0',
    unreadCount: 3,
    lastMessage: 'Hola, ¿me puedes ayudar con mi pedido?',
    lastTime: '10:42 AM',
    aiAgentEnabled: true,
    originPlatform: 'whatsapp',
    platform: 'whatsapp',
    linkedPlatforms: ['whatsapp', 'instagram'],
    leadLevel: 3,
    isOnline: true,
  },
  {
    id: 'contact-2',
    name: 'Carlos Andrade',
    email: 'carlos.andrade@example.com',
    phone: '+593 98 765 4321',
    city: 'Guayaquil',
    leadType: 'Producto',
    interest: 'Catálogo',
    source: 'instagram',
    leadStage: 'Lead',
    purchases: 0,
    unreadCount: 1,
    lastMessage: 'Gracias por la información 👍',
    lastTime: '10:15 AM',
    originPlatform: 'instagram',
    platform: 'instagram',
    linkedPlatforms: ['instagram', 'whatsapp'],
    leadLevel: 2,
    isOnline: true,
  },
  {
    id: 'contact-3',
    name: 'Lucía Pérez',
    email: 'lucia.perez@example.com',
    phone: '+593 97 555 1234',
    city: 'Cuenca',
    leadType: 'Servicio',
    interest: 'Plan Premium',
    source: 'messenger',
    leadStage: 'Scheduled',
    purchases: '0',
    unreadCount: 0,
    lastMessage: '¿Cuándo hay disponibilidad?',
    lastTime: '9:58 AM',
    originPlatform: 'messenger',
    platform: 'messenger',
    linkedPlatforms: ['messenger'],
    leadLevel: 4,
    isOnline: false,
  },
  {
    id: 'contact-4',
    name: 'Jorge Luis',
    email: 'jorge.luis@example.com',
    phone: '+593 96 888 0001',
    city: 'Ambato',
    leadType: 'Producto',
    interest: 'Social Commerce',
    source: 'whatsapp',
    leadStage: 'Purchased',
    purchases: 2,
    unreadCount: 5,
    lastMessage: 'Perfecto, lo reviso y te confirmo.',
    lastTime: '9:30 AM',
    originPlatform: 'whatsapp',
    platform: 'whatsapp',
    linkedPlatforms: ['whatsapp', 'instagram'],
    leadLevel: 5,
    isOnline: true,
  },
  {
    id: 'contact-5',
    name: 'Valentina Rizzo',
    email: 'valentina.rizzo@example.com',
    phone: '+593 95 111 2233',
    city: 'Manta',
    leadType: 'Servicio',
    interest: 'Automatización',
    source: 'instagram',
    leadStage: 'Checkout',
    purchases: 1,
    unreadCount: 0,
    lastMessage: 'Me interesa el plan premium',
    lastTime: '8:45 AM',
    originPlatform: 'instagram',
    platform: 'instagram',
    linkedPlatforms: ['instagram', 'whatsapp'],
    leadLevel: 4,
    isOnline: false,
  },
];

export default DEMO_CRM_CONTACTS;